NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: intermediatecerts/localhost-9056.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: intermediatecerts/localhost-9056.pem
    OrganizationalUnitIdentifier: peer
